// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvSlRZWkKRMXqhlWI2w66o9MevXolOw-k',
    appId: '1:28180153345:web:d7a8c524cab12ea2256c00',
    messagingSenderId: '28180153345',
    projectId: 'icthub-project',
    authDomain: 'icthub-project.firebaseapp.com',
    storageBucket: 'icthub-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcB-hzLQgjbNHtcD_VU2-WYOcthvb6kl4',
    appId: '1:28180153345:android:e83e70fe88fa4546256c00',
    messagingSenderId: '28180153345',
    projectId: 'icthub-project',
    storageBucket: 'icthub-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANmfglkCfowyBity6RQ48Zd86UmQkXQBI',
    appId: '1:28180153345:ios:ea1f8e96fb36cabe256c00',
    messagingSenderId: '28180153345',
    projectId: 'icthub-project',
    storageBucket: 'icthub-project.appspot.com',
    iosBundleId: 'com.example.icthub',
  );
}
